
# A variable is an object that stores data 

# types of variables are as follow 
# 1. Global variables
# 2. Local or Task variables 
# 3. User defined (Taking input from user)

# {{ variable name }} ----- this is a Jinja technique 


# below is the example of Global variable 
- name: Demo on vars 
  hosts: localhost
  vars:
    URL_PLAY: This is an example of global variable
  tasks:
    - name: Global variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}  

    - name: Global variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}    

# below is the example of local/task variable 
    - name: Task variable
      ansible.builtin.debug:
        msg: URL_Task - {{ URL_Task }}
      vars:
        URL_TASK: This is an example of local variable 




        