---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copy index.html to web root
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Copy apache2.conf file
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
  notify: Restart apache

# tasks file for roles_assignment
